version: "3.8"

services:
  backend:
    container_name: cod_backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - catsordogs_net
    command: sh -c "sleep 5 && ./main"

  database:
    container_name: cod_db
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./cod-data:/var/lib/postgresql/data:rw
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - catsordogs_net

networks:
  catsordogs_net:
