apiVersion: apps/v1
kind: Deployment
metadata:
  name: cod-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catsordogs
  template:
    metadata:
      labels:
        app: catsordogs
    spec:
      containers:
        - name: catsordogs
          image: nsahil992/catsordogs:v1
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: postgres-secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgres-secret
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_DB
                  name: postgres-secret
