apiVersion: v1
kind: Service
metadata:
  name: cod-service
spec:
  selector:
    app: catsordogs
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30102
      protocol: TCP